import crypto from 'crypto'
import fs   from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import type { CatalogIndexEntry } from './catalog.js'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
export const TEMPLATES_DIR = path.resolve(__dirname, '../templates')
export const CATALOG_INDEX_FILE = path.resolve(__dirname, '../catalog.index.json')

/** Three-way classification against the installed base (ADR-006, per id).
 *  clean      = local untouched, upstream changed   → safe fast-forward
 *  customized = local changed, upstream unchanged   → skipped, nothing new
 *  conflict   = both changed                        → never auto-applied
 *  unknown    = no base recorded                    → legacy behavior */
export type MergeState = 'clean' | 'customized' | 'conflict' | 'unknown'

/**
 * templates/ uses a logical layout (skills/, rules/, agents/, context/, root files).
 * This table maps each template-relative path to its install location (ADR-002).
 */
export function mapTemplatePath(rel: string): string {
  const posix = rel.split(path.sep).join('/')
  if (posix.startsWith('skills/')) {
    const name = path.basename(posix, '.md')
    return path.join('.claude', 'skills', name, 'SKILL.md')
  }
  if (posix.startsWith('rules/'))
    return path.join('.claude', 'rules', path.basename(posix))
  if (posix.startsWith('agents/'))
    return path.join('.claude', 'agents', path.basename(posix))
  if (posix.startsWith('context/'))
    return path.join('.context', posix.slice('context/'.length))
  return rel   // root-level files (CLAUDE.md) install verbatim
}

/** The compiled catalog index (ADR-018): the entries `suggest` filters against.
 *  Generated by scripts/build-catalog.mjs; never hand-edited. */
export function loadCatalogIndex(): CatalogIndexEntry[] {
  if (!fs.existsSync(CATALOG_INDEX_FILE)) return []
  try {
    const parsed = JSON.parse(fs.readFileSync(CATALOG_INDEX_FILE, 'utf8'))
    return Array.isArray(parsed.entries) ? parsed.entries : []
  } catch {
    return []
  }
}

export function hashContent(content: string | Buffer): string {
  return 'sha256:' + crypto.createHash('sha256').update(content).digest('hex')
}

/** Copy one resolved file action to its install location. A legacy install may
 *  have left a symlink at the destination (e.g. CLAUDE.md → .ai/AI_CONTEXT.md);
 *  replace the link itself, never write through it. */
export function applyAction(action: { type: 'create' | 'update'; src: string; dest: string }): void {
  fs.mkdirSync(path.dirname(action.dest), { recursive: true })
  try {
    if (fs.lstatSync(action.dest).isSymbolicLink()) fs.unlinkSync(action.dest)
  } catch { /* dest does not exist */ }
  fs.copyFileSync(action.src, action.dest)
}

function walkDir(dir: string, cb: (f: string) => void): void {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, e.name)
    if (e.isDirectory()) walkDir(full, cb)
    else cb(full)
  }
}

const logicalRel = (src: string): string =>
  path.relative(TEMPLATES_DIR, src).split(path.sep).join('/')

// ─── ADR-017 §3: state keyed by catalog entry id ───────────────────────────

export const SCAFFOLD_STATE_FILE = '.claude/.scaffold-state.json'
export const STATE_SCHEMA_VERSION = 1

/** One installed catalog entry, tracked by id (ADR-017 §3). `hash`/`version`
 *  are the catalog base at reconcile time: `update` compares the on-disk file
 *  against `hash` (local drift) and the catalog against `version` (upstream
 *  change). The unit of tracking is the entry id, not the raw file path. */
export interface InstalledEntry {
  version:    string
  hash:       string
  merge:      MergeState
  workspaces: string[]
}

/** The id-keyed install state (ADR-017 §3), at `.claude/.scaffold-state.json`. */
export interface ScaffoldState {
  schemaVersion: number
  installedAt:   string
  installed:     Record<string, InstalledEntry>
}

/** One entry the curation (`ai-init`) decided to install, with the workspaces
 *  that justified it (ADR-020 §2). The input unit of `apply`. */
export interface ApplyItem {
  entry:      CatalogIndexEntry
  workspaces: string[]
}

/** Version file written by install and read by ai-init. */
export interface ScaffoldVersion {
  version: string
  installedAt: string
}

/** What `apply` did to one entry, for the command layer to render. */
export interface AppliedAction {
  id:    string
  type:  'create' | 'update' | 'skip'
  dest:  string
  merge: MergeState
}

export interface McpMergeResult {
  added:   string[]
  skipped: string[]
  /** true when an existing .mcp.json could not be parsed; nothing was written. */
  invalid: boolean
}

export interface ApplyResult {
  actions: AppliedAction[]
  mcp:     McpMergeResult
  state:   ScaffoldState
}

/** Read the id-keyed state. null when absent or unparseable. */
export function readState(projectRoot: string): ScaffoldState | null {
  const p = path.join(projectRoot, SCAFFOLD_STATE_FILE)
  if (!fs.existsSync(p)) return null
  try {
    const parsed = JSON.parse(fs.readFileSync(p, 'utf8'))
    if (typeof parsed !== 'object' || parsed === null) return null
    const installed = (parsed as Record<string, unknown>).installed
    if (typeof installed !== 'object' || installed === null) return null
    return parsed as ScaffoldState
  } catch {
    return null
  }
}

export function writeState(projectRoot: string, state: ScaffoldState): void {
  const p = path.join(projectRoot, SCAFFOLD_STATE_FILE)
  fs.mkdirSync(path.dirname(p), { recursive: true })
  fs.writeFileSync(p, JSON.stringify(state, null, 2) + '\n')
}

export const VERSION_FILE = '.claude/scaffold-version.json'

/** Read the installed version. Returns null if not installed. */
export function readVersion(projectRoot: string): ScaffoldVersion | null {
  const p = path.join(projectRoot, VERSION_FILE)
  if (!fs.existsSync(p)) return null
  try {
    const parsed = JSON.parse(fs.readFileSync(p, 'utf8'))
    if (typeof parsed !== 'object' || parsed === null) return null
    const version = (parsed as Record<string, unknown>).version
    if (typeof version !== 'string') return null
    return parsed as ScaffoldVersion
  } catch {
    return null
  }
}

/** Write the installed version. */
export function writeVersion(projectRoot: string, versionInfo: ScaffoldVersion): void {
  const p = path.join(projectRoot, VERSION_FILE)
  fs.mkdirSync(path.dirname(p), { recursive: true })
  fs.writeFileSync(p, JSON.stringify(versionInfo, null, 2) + '\n')
}

/** Get the current package version from local package.json. */
export function getCurrentPackageVersion(): string | null {
  const packagePath = path.resolve(fileURLToPath(import.meta.url), '../../package.json')
  try {
    const pkg = JSON.parse(fs.readFileSync(packagePath, 'utf8'))
    return (pkg as Record<string, unknown>).version as string || null
  } catch {
    return null
  }
}

/** Get the remote version from git tags. Returns null if unavailable. */
export async function getRemoteVersion(): Promise<string | null> {
  try {
    const { execSync } = await import('child_process')
    const stdout = execSync('git ls-remote --tags github-achieve:jcuadros-achieve/ai-scaffold', {
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore']
    })
    // Find 'latest' tag or get the highest versioned tag
    const tags = stdout
      .split('\n')
      .filter(line => line.includes('refs/tags/'))
      .map(line => {
        const match = line.match(/refs\/tags\/(?:v)?(\d+\.\d+\.\d+)/)
        return match ? match[1] : null
      })
      .filter((v): v is string => v !== null)
    if (tags.length === 0) return null
    // Return highest version (simple string comparison works for semver)
    return tags.sort().reverse()[0]
  } catch {
    return null
  }
}

/** Classify a body-bearing entry against its recorded base (ADR-006, per id).
 *  No base → 'unknown' (legacy). Identical → 'clean' skip. Both changed →
 *  'conflict', never auto-applied. */
function classifyEntry(
  dest: string, incoming: string, baseHash: string | undefined,
): { type: 'create' | 'update' | 'skip'; merge: MergeState } {
  if (!fs.existsSync(dest)) return { type: 'create', merge: 'clean' }
  const current = fs.readFileSync(dest, 'utf8')
  if (current === incoming) return { type: 'skip', merge: 'clean' }
  if (!baseHash) return { type: 'update', merge: 'unknown' }
  const localModified    = hashContent(current)  !== baseHash
  const upstreamModified = hashContent(incoming) !== baseHash
  if (localModified && !upstreamModified) return { type: 'skip', merge: 'customized' }
  if (localModified && upstreamModified)  return { type: 'skip', merge: 'conflict' }
  return { type: 'update', merge: 'clean' }
}

/** The server name written into .mcp.json for an mcp entry (id minus prefix). */
function mcpServerName(id: string): string {
  return id.replace(/^mcp\//, '')
}

/** Add one mcp entry's server config to .mcp.json, add-only (ADR-008): the
 *  user file wins, an existing server is never overwritten, an unparseable
 *  file is left untouched. */
function applyMcpEntry(
  projectRoot: string, entry: CatalogIndexEntry,
): 'added' | 'skipped' | 'invalid' {
  if (!entry.server) return 'skipped'
  const p = path.join(projectRoot, '.mcp.json')
  let data: Record<string, unknown> = {}
  if (fs.existsSync(p)) {
    try { data = JSON.parse(fs.readFileSync(p, 'utf8')) }
    catch { return 'invalid' }
  }
  const servers = (typeof data.mcpServers === 'object' && data.mcpServers !== null
    ? data.mcpServers : {}) as Record<string, unknown>
  data.mcpServers = servers
  const name = mcpServerName(entry.id)
  if (name in servers) return 'skipped'
  servers[name] = entry.server
  fs.writeFileSync(p, JSON.stringify(data, null, 2) + '\n')
  return 'added'
}

/**
 * The single writer (ADR-017 §2/§5). Given the curated plan, write each
 * body-bearing entry to its install location, classify it three-way against the
 * recorded base per id (ADR-006), merge any mcp entries add-only, and persist
 * the new id-keyed state. Conflicts are never auto-applied. Prior state for ids
 * not in the plan is preserved (deselecting never deletes user files). PURE of
 * UI — the command layer renders the returned actions.
 */
export function apply(projectRoot: string, items: ApplyItem[]): ApplyResult {
  const prior = readState(projectRoot)
  const installed: Record<string, InstalledEntry> = { ...(prior?.installed ?? {}) }
  const actions: AppliedAction[] = []
  const mcp: McpMergeResult = { added: [], skipped: [], invalid: false }

  for (const { entry, workspaces } of items) {
    const base = { version: entry.version ?? '', hash: entry.hash ?? '', workspaces }

    if (entry.surface === 'mcp') {
      const r = applyMcpEntry(projectRoot, entry)
      if (r === 'added')   mcp.added.push(entry.id)
      if (r === 'skipped') mcp.skipped.push(entry.id)
      if (r === 'invalid') mcp.invalid = true
      const merge: MergeState = r === 'added' ? 'clean' : 'customized'
      installed[entry.id] = { ...base, merge }
      actions.push({ id: entry.id, type: r === 'added' ? 'create' : 'skip',
        dest: '.mcp.json', merge })
      continue
    }

    if (!entry.body) continue
    const dest = path.join(projectRoot, mapTemplatePath(entry.body))
    const src  = path.join(TEMPLATES_DIR, entry.body)
    const incoming = fs.readFileSync(src, 'utf8')
    const { type, merge } = classifyEntry(dest, incoming, installed[entry.id]?.hash)
    if (type !== 'skip') applyAction({ type, src, dest })
    installed[entry.id] = { ...base, merge }
    actions.push({ id: entry.id, type, dest, merge })
  }

  const state: ScaffoldState = {
    schemaVersion: STATE_SCHEMA_VERSION,
    installedAt:   new Date().toISOString(),
    installed,
  }
  writeState(projectRoot, state)
  return { actions, mcp, state }
}

// ─── ADR-017 §1: the seed (bootstrap for ai-init) ──────────────────────────

export interface SeedFile {
  type: 'create' | 'skip'
  src:  string
  dest: string
}

export interface SeedResult {
  /** Infrastructure files (CLAUDE.md, .context/**) laid by the seed. */
  files: SeedFile[]
  /** Result of applying the seed catalog entries (ai-init, context rule). */
  apply: ApplyResult
}

/**
 * Lay only the seed (ADR-017 §1): the minimum for `ai-init` to run, nothing
 * else. Two parts: (1) every template file NOT owned by a catalog entry —
 * pure infrastructure (CLAUDE.md, .context/INDEX.md, the empty adr/ai-log
 * scaffolds) — created if absent, never clobbered; (2) the catalog entries
 * marked `seed: true` (ai-init skill, context rule), applied through the single
 * writer so they are recorded in id-keyed state. `install` produces a
 * bootstrap, not a usable scaffold — selection moves to `ai-init`.
 */
export function installSeed(projectRoot: string): SeedResult {
  const index = loadCatalogIndex()
  const catalogBodies = new Set(
    index.filter(e => e.surface !== 'mcp' && e.body).map(e => e.body as string))

  const files: SeedFile[] = []
  walkDir(TEMPLATES_DIR, (src) => {
    const rel = logicalRel(src)
    if (rel.startsWith('mcp/')) return          // mcp catalog source (no body); never a file
    if (catalogBodies.has(rel)) return          // catalog-owned; handled below
    const dest = path.join(projectRoot, mapTemplatePath(rel))
    if (fs.existsSync(dest)) { files.push({ type: 'skip', src, dest }); return }
    applyAction({ type: 'create', src, dest })
    files.push({ type: 'create', src, dest })
  })

  const seedItems: ApplyItem[] = index
    .filter(e => e.seed)
    .map(entry => ({ entry, workspaces: [] }))
  const result = apply(projectRoot, seedItems)

  // Write the current version
  const currentVersion = getCurrentPackageVersion()
  if (currentVersion) {
    writeVersion(projectRoot, {
      version: currentVersion,
      installedAt: new Date().toISOString()
    })
  }

  return { files, apply: result }
}

// ─── read-only reconciliation for status/diff/update ───────────────────────

/** One installed entry reconciled against the current catalog. */
export interface Reconciled {
  id:        string
  /** The entry in the current catalog, if it still exists there. */
  entry?:    CatalogIndexEntry
  installed: InstalledEntry
  type:      'update' | 'skip' | 'missing'
  merge:     MergeState
  dest?:     string
  /** Incoming template body (body entries with a catalog match). */
  incoming?: string
  /** Current on-disk content (body entries). */
  current?:  string
  /** The catalog version moved past the recorded base. */
  upstreamChanged: boolean
}

/**
 * Reconcile installed state against the current catalog, read-only (no writes).
 * For each installed id, look it up in the catalog and classify the on-disk
 * file three-way against the recorded base. Shared by `status`, `diff`, and
 * `update` so they stay coherent (ADR-017 §3).
 */
export function reconcile(
  projectRoot: string, catalog: CatalogIndexEntry[] = loadCatalogIndex(),
): Reconciled[] {
  const state = readState(projectRoot)
  if (!state) return []
  const byId = new Map(catalog.map(e => [e.id, e]))
  const out: Reconciled[] = []

  for (const [id, installed] of Object.entries(state.installed)) {
    const entry = byId.get(id)
    const upstreamChanged = Boolean(entry && (entry.hash ?? '') !== installed.hash)

    if (entry?.surface === 'mcp') {
      const p = path.join(projectRoot, '.mcp.json')
      let present = false
      try { present = mcpServerName(id) in (JSON.parse(fs.readFileSync(p, 'utf8')).mcpServers ?? {}) }
      catch { present = false }
      out.push({ id, entry, installed,
        type: present ? 'skip' : 'update', merge: present ? 'customized' : 'clean',
        upstreamChanged })
      continue
    }

    if (!entry || !entry.body) {
      // id no longer in the catalog (or bodiless): nothing to update.
      out.push({ id, entry, installed, type: 'missing', merge: installed.merge, upstreamChanged })
      continue
    }

    const dest = path.join(projectRoot, mapTemplatePath(entry.body))
    const src  = path.join(TEMPLATES_DIR, entry.body)
    const incoming = fs.existsSync(src) ? fs.readFileSync(src, 'utf8') : ''
    const current  = fs.existsSync(dest) ? fs.readFileSync(dest, 'utf8') : undefined
    const { type, merge } = classifyEntry(dest, incoming, installed.hash)
    out.push({ id, entry, installed,
      type: type === 'create' ? 'update' : type, merge,
      dest, incoming, current, upstreamChanged })
  }
  return out
}
